from pathlib import Path
import ast, hashlib, json, re, sqlite3, subprocess, sys, tempfile
ROOT=Path(__file__).resolve().parents[1]
RESULTS=[]
TESTS=["required_pg_u04_tree_present", "exact_pg_u04_new_path_set", "json_files_parse", "schemas_draft_2020_12", "approved_subset_schema_valid", "exact_three_source_refs", "source_hashes_match_mapping", "option_A_selection_recorded", "accepted_count_deltas_exact", "schema_has_57_tables_8_views", "seed_manifest_has_11_tables_140_rows", "seed_files_hash_match", "seed_row_counts_match", "stable_primary_keys_match_inventory", "no_sqlite_binary_tracked", "no_private_operational_records", "schema_sql_has_all_objects", "builder_stdlib_only", "builder_uses_git_native_inputs", "builder_does_not_read_source_db", "generated_db_build_one_pass", "generated_db_build_two_pass", "generated_db_hashes_equal", "generated_db_quick_check_ok", "generated_db_fk_check_clean", "generated_db_views_compile", "generated_db_table_count_57", "generated_db_view_count_8", "generated_db_seed_rows_140", "generated_db_empty_tables_46", "generated_db_rowsets_match_source_inventory", "PG_U04_ledger_record_present", "PG_U04_dependencies_exact", "PG_U04_commit_gate_pending", "PG_U03_post_commit_residual_resolved", "PG_U03_exact_commit_bound", "PG_U04_source_refs_registered", "PG_U04_evidence_refs_registered", "option_A_evidence_consumed", "compatibility_records_no_authority", "PG_U04_checksum_manifest_matches", "prior_unit_regressions_pass", "PG_U03_validator_growth_safe", "claim_boundaries_false", "root_README_registers_PG_U04", "docs_register_generated_DB_boundary", "private_and_generated_artifacts_absent", "test_matrix_matches_validator", "base_HEAD_locked", "candidate_not_canon", "SQLite_binary_excluded_by_gitignore", "deterministic_builder_output_metadata", "schema_inventory_columns_present", "all_57_table_definitions_nonempty", "all_8_view_definitions_nonempty", "seed_jsonl_canonical_lines", "patch_004_present_only_as_candidate_rule", "P1_P2_P7_real_records_absent", "bulk_archive_seed_rows_absent", "db_meta_candidate_state_preserved", "Human_gate_required_before_commit", "source_apply_false", "DB_write_false", "runtime_activation_false", "publish_false", "unit_scope_is_PG_U04_only", "Windows_CRLF_canonical_hash_ready", "disposable_build_output_outside_repo", "source_DB_hash_not_repo_blob"]
CLAIM_KEYS=["source_apply", "DB_write", "RLDB_writeback", "canon", "commit", "push", "publish", "runtime_activation"]
SEED_TABLES=["sun_layers", "gates", "force_flows", "force_skills", "projects", "force_cell_families", "force_cells", "full_force_objects", "project_cell_refs", "patch_candidates", "db_meta"]
EXPECTED_HASHES={"PGU04-SRC-A01":"eefa0b57f01d2f88e93f6351faf6a57773cc1995069c255f4afe9ed49ada08eb","PGU04-SRC-A02":"f48866b47098cd0a64471cc50cb53a89d32983d56db207a81c97727824afb1dc","PGU04-SRC-A03":"23f05ef8bc0144dbf8b6a74059ec037fde477327619d81ef949e18ca7802b09a"}
PG_U04_COMMIT="3bd2c1d4685d1519b02e559f33f09185ef20de79"
PG_U04_TREE="8be476f59d6b6595046c64a4b212878d57f261a3"
def check(n,c,d=''): RESULTS.append((n,'PASS' if c else 'FAIL','' if c else d))
def load(p): return json.loads((ROOT/p).read_text(encoding='utf-8'))
def cb(p): return (ROOT/p).read_bytes().replace(b'\r\n',b'\n').replace(b'\r',b'\n')
def sh(p): return hashlib.sha256(cb(p)).hexdigest()
subset=load('data/sun-graph/approved-public-subset.json'); inv=load('data/sun-graph/schema-inventory.json'); ledger=load('data/source-ledger/public-unit-ledger.json'); units={u['unit_id']:u for u in ledger['units']}; u4=units.get('PG-U04',{});u3=units['PG-U03']
tree_readback=subprocess.run(['git','rev-parse',f'{PG_U04_COMMIT}^{{tree}}'],cwd=ROOT,text=True,capture_output=True);pg_u04_tree=tree_readback.stdout.strip() if tree_readback.returncode==0 else ''
new_paths=['src/sun-graph/sun-graph-doctrine-contract.md','migrations/sun-graph/001_schema.sql','data/sun-graph/approved-public-subset.json','data/sun-graph/schema-inventory.json','data/sun-graph/pg-u04-checksum-manifest.json','schemas/sun-graph/approved-public-subset.schema.json','schemas/sun-graph/seed-manifest-entry.schema.json','tools/build_sun_graph_db.py','docs/sun-graph/README.md','tests/PG_U04_TEST_MATRIX.json','tests/validate_pg_u04.py']+[f'data/sun-graph/seeds/{t}.jsonl' for t in SEED_TABLES]
check('required_pg_u04_tree_present',all((ROOT/p).is_file() for p in new_paths))
actual={p.relative_to(ROOT).as_posix() for p in ROOT.rglob('*') if p.is_file() and (('sun-graph' in p.parts) or p.name in ('PG_U04_TEST_MATRIX.json','validate_pg_u04.py') or p.as_posix().endswith('tools/build_sun_graph_db.py'))}
check('exact_pg_u04_new_path_set',actual==set(new_paths),str(sorted(actual^set(new_paths))))
json_paths=[p for p in new_paths if p.endswith('.json')]; parsed={}; errs=[]
for p in json_paths:
 try: parsed[p]=load(p)
 except Exception as e: errs.append(f'{p}:{e}')
check('json_files_parse',not errs,str(errs));check('schemas_draft_2020_12',all(parsed[p].get('$schema')=='https://json-schema.org/draft/2020-12/schema' for p in json_paths if p.startswith('schemas/')))
schema=parsed['schemas/sun-graph/approved-public-subset.schema.json'];check('approved_subset_schema_valid',all(k in subset for k in schema['required']) and set(subset)<=set(schema['properties']))
refs={x['source_ref_id']:x['sha256'] for x in u4.get('source_hashes',[])};check('exact_three_source_refs',list(refs)==list(EXPECTED_HASHES));check('source_hashes_match_mapping',refs==EXPECTED_HASHES)
hs=subset['human_selection'];check('option_A_selection_recorded',hs['selected_option']=='option_A' and hs['schema_scope']=={'tables':57,'views':8} and hs['seed_scope']=={'rows':140,'nonempty_tables':11})
check('accepted_count_deltas_exact',hs['accepted_deltas']==['full_force_objects_39_not_role_map_38','db_meta_12_not_role_map_9','project_cell_refs_20_inferred_candidate_rows','patch_candidates_1_public_ingest_rule_candidate'])
check('schema_has_57_tables_8_views',len(inv['tables'])==57 and len(inv['views'])==8)
seeds=subset['git_native']['seed_files'];check('seed_manifest_has_11_tables_140_rows',len(seeds)==11 and sum(x['row_count'] for x in seeds)==140 and [x['table'] for x in seeds]==SEED_TABLES)
check('seed_files_hash_match',all(sh(x['path'])==x['jsonl_sha256'] for x in seeds));check('seed_row_counts_match',all(sum(1 for l in (ROOT/x['path']).read_text(encoding='utf-8').splitlines() if l)==x['row_count'] for x in seeds))
check('stable_primary_keys_match_inventory',all(x['primary_key'] for x in seeds))
allfiles=[p.relative_to(ROOT).as_posix() for p in ROOT.rglob('*') if p.is_file() and '.git' not in p.parts]
check('no_sqlite_binary_tracked',not any(p.endswith(('.db','.sqlite','.sqlite3')) for p in allfiles));check('no_private_operational_records',subset['public_boundary']=={'private_operational_records_included':False,'P1_P2_P7_records_included':False,'bulk_archive_rows_included':False,'sqlite_binary_included':False})
sql=(ROOT/'migrations/sun-graph/001_schema.sql').read_text(encoding='utf-8');check('schema_sql_has_all_objects',sql.count('CREATE TABLE')+sql.count('CREATE TABLE IF NOT EXISTS')>=57 and sql.count('CREATE VIEW')+sql.count('CREATE VIEW IF NOT EXISTS')>=8)
syntax=ast.parse((ROOT/'tools/build_sun_graph_db.py').read_text(encoding='utf-8')); imports=set()
for n in ast.walk(syntax):
 if isinstance(n,ast.Import): imports.update(a.name.split('.')[0] for a in n.names)
 elif isinstance(n,ast.ImportFrom) and n.module: imports.add(n.module.split('.')[0])
check('builder_stdlib_only',imports<={'__future__','argparse','hashlib','json','sqlite3','pathlib'});btxt=(ROOT/'tools/build_sun_graph_db.py').read_text(encoding='utf-8');check('builder_uses_git_native_inputs','001_schema.sql' in btxt and 'approved-public-subset.json' in btxt);check('builder_does_not_read_source_db','DZN32_SUN_GRAPH' not in btxt and 'mode=ro' not in btxt)
with tempfile.TemporaryDirectory() as td:
 a=Path(td)/'a.db';b=Path(td)/'b.db';pa=subprocess.run([sys.executable,'-S',str(ROOT/'tools/build_sun_graph_db.py'),'--output',str(a)],cwd=ROOT,text=True,capture_output=True);pb=subprocess.run([sys.executable,'-S',str(ROOT/'tools/build_sun_graph_db.py'),'--output',str(b)],cwd=ROOT,text=True,capture_output=True)
 check('generated_db_build_one_pass',pa.returncode==0,pa.stderr);check('generated_db_build_two_pass',pb.returncode==0,pb.stderr);ha=hashlib.sha256(a.read_bytes()).hexdigest() if a.exists() else '';hb=hashlib.sha256(b.read_bytes()).hexdigest() if b.exists() else '';check('generated_db_hashes_equal',ha==hb and bool(ha),f'{ha} {hb}')
 con=sqlite3.connect(a);con.row_factory=sqlite3.Row;quick=con.execute('pragma quick_check').fetchall();fk=con.execute('pragma foreign_key_check').fetchall();tc=con.execute("select count(*) from sqlite_master where type='table' and name not like 'sqlite_%'").fetchone()[0];vc=con.execute("select count(*) from sqlite_master where type='view'").fetchone()[0];counts={t:con.execute(f'SELECT count(*) FROM "{t}"').fetchone()[0] for t in SEED_TABLES};empty=tc-sum(1 for v in counts.values() if v>0);[con.execute(f'SELECT * FROM "{r[0]}" LIMIT 0').fetchall() for r in con.execute("select name from sqlite_master where type='view'")]
 rowset_ok=True
 for ent in seeds:
  pks=ent['primary_key'];order=','.join('"'+x+'"' for x in pks);rows=[dict(r) for r in con.execute(f'SELECT * FROM "{ent["table"]}" ORDER BY {order}')];digest=hashlib.sha256(json.dumps(rows,sort_keys=True,ensure_ascii=False,separators=(',',':')).encode()).hexdigest();rowset_ok=rowset_ok and digest==ent['source_canonical_rowset_sha256']
 con.close()
 check('generated_db_quick_check_ok',[tuple(x) for x in quick]==[('ok',)]);check('generated_db_fk_check_clean',not fk,str(fk));check('generated_db_views_compile',vc==8);check('generated_db_table_count_57',tc==57);check('generated_db_view_count_8',vc==8);check('generated_db_seed_rows_140',sum(counts.values())==140);check('generated_db_empty_tables_46',empty==46)
 check('generated_db_rowsets_match_source_inventory',rowset_ok)
check('PG_U04_ledger_record_present',u4.get('name')=='sun_graph_doctrine_git_native_core' and u4.get('migration_order')==5);check('PG_U04_dependencies_exact',u4.get('dependency_unit_ids')==['PG-U00','PG-U01','PG-U03']);check('PG_U04_commit_gate_pending',u4.get('human_gate',{}).get('state')=='repository_commit_gate_consumed_canon_gate_pending' and u4.get('repository_binding',{}).get('mode')=='exact_commit' and u4.get('repository_binding',{}).get('commit_sha')==PG_U04_COMMIT and pg_u04_tree==PG_U04_TREE)
ev={e['evidence_id']:e for e in load('data/source-ledger/evidence-reference-registry.json')['evidence']};check('PG_U03_post_commit_residual_resolved',u3['human_gate']['state']=='repository_commit_gate_consumed_canon_gate_pending' and ev['PGU03-E03']['state']=='COMMIT_GATE_CONSUMED' and ev['PGU03-E04']['state']=='PASS_POST_PUSH');check('PG_U03_exact_commit_bound',u3['repository_binding']['commit_sha']=='34f7caa61c9aa8afe8723170bb50982ab406e2f3')
sr={r['source_ref_id']:r for r in load('data/source-ledger/source-reference-registry.json')['references']};check('PG_U04_source_refs_registered',all(k in sr and sr[k]['sha256']==v for k,v in EXPECTED_HASHES.items()));check('PG_U04_evidence_refs_registered',all(k in ev for k in ['PGU04-E01','PGU04-E02','PGU04-E03','PGU04-E04']));check('option_A_evidence_consumed',ev['PGU04-E02']['state']=='PUBLIC_SUBSET_GATE_CONSUMED_OPTION_A')
cr={r['record_id']:r for r in load('data/source-ledger/compatibility-registry.json')['records']};check('compatibility_records_no_authority',all(cr[k]['authority_effect']=='none' and cr[k]['can_promote_canon'] is False for k in ['PGU04-COMPAT-REPAIRED-CANDIDATE-v0_1_2','PGU04-COMPAT-GENERATED-SQLITE']))
man=load('data/sun-graph/pg-u04-checksum-manifest.json');mm={x['path']:x['sha256'] for x in man['files']};check('PG_U04_checksum_manifest_matches',mm=={p:sh(p) for p in mm} and man['self_included'] is False)
outs=[]
for u,c in [('00',35),('01',40),('02',50),('03',60)]:
 pr=subprocess.run([sys.executable,'-S',str(ROOT/f'tests/validate_pg_u{u}.py')],cwd=ROOT,text=True,capture_output=True);outs.append(pr.returncode==0 and f'SUMMARY\tPASS={c}\tFAIL=0' in pr.stdout)
check('prior_unit_regressions_pass',all(outs),str(outs));check('PG_U03_validator_growth_safe','PG_U03_commit_gate_consumed' in load('tests/PG_U03_TEST_MATRIX.json')['tests']);claims=[subset['claim_boundary'],u4['claim_boundary'],ledger['claim_boundary']];check('claim_boundaries_false',all(set(c)==set(CLAIM_KEYS) and all(v is False for v in c.values()) for c in claims));check('root_README_registers_PG_U04','PG-U04' in (ROOT/'README.md').read_text());check('docs_register_generated_DB_boundary','not tracked' in (ROOT/'docs/sun-graph/README.md').read_text())
check('private_and_generated_artifacts_absent',not any(p.endswith(('.db','.sqlite','.zip','SHA256SUMS.txt','VALIDATION_OUTPUT.txt')) or p.startswith(('peer_evidence/','dist/','build/')) for p in allfiles));matrix=load('tests/PG_U04_TEST_MATRIX.json');check('test_matrix_matches_validator',matrix['tests']==TESTS and matrix['expected_pass_count']==len(TESTS));check('base_HEAD_locked',u4['repository_binding']['base_commit']=='34f7caa61c9aa8afe8723170bb50982ab406e2f3');check('candidate_not_canon',u4['state']=='GIT_CANDIDATE' and u4['canon'] is False);check('SQLite_binary_excluded_by_gitignore','*.db' in (ROOT/'.gitignore').read_text());check('deterministic_builder_output_metadata',pa.returncode==0 and 'sha256' in pa.stdout);check('schema_inventory_columns_present',all(x['columns'] for x in inv['tables']));check('all_57_table_definitions_nonempty',all(x['sql_sha256'] for x in inv['tables']));check('all_8_view_definitions_nonempty',all(x['sql_sha256'] for x in inv['views']));check('seed_jsonl_canonical_lines',all(all(json.dumps(json.loads(l),ensure_ascii=False,separators=(',',':'))==l for l in (ROOT/x['path']).read_text(encoding='utf-8').splitlines() if l) for x in seeds));pc=[json.loads(l) for l in (ROOT/'data/sun-graph/seeds/patch_candidates.jsonl').read_text().splitlines() if l];check('patch_004_present_only_as_candidate_rule',len(pc)==1 and pc[0]['candidate_id']=='PATCH-004');check('P1_P2_P7_real_records_absent',subset['public_boundary']['P1_P2_P7_records_included'] is False);check('bulk_archive_seed_rows_absent',not any(x['table']=='archive_lineage' for x in seeds));meta={json.loads(l)['key']:json.loads(l)['value'] for l in (ROOT/'data/sun-graph/seeds/db_meta.jsonl').read_text().splitlines() if l};check('db_meta_candidate_state_preserved','candidate' in meta.get('status',''));check('Human_gate_required_before_commit',u4['human_gate']['state']=='repository_commit_gate_consumed_canon_gate_pending' and u4['human_gate']['exact_scope']=='PG-U04' and u4['state']=='GIT_CANDIDATE' and u4['canon'] is False);check('source_apply_false',all(c['source_apply'] is False for c in claims));check('DB_write_false',all(c['DB_write'] is False for c in claims));check('runtime_activation_false',all(c['runtime_activation'] is False for c in claims));check('publish_false',all(c['publish'] is False for c in claims));check('unit_scope_is_PG_U04_only',not any('PG-U05' in p for p in allfiles));check('Windows_CRLF_canonical_hash_ready',all(hashlib.sha256((ROOT/p).read_bytes().replace(b'\r\n',b'\n').replace(b'\r',b'\n')).hexdigest()==sh(p) for p in mm));check('disposable_build_output_outside_repo',not any(p.endswith('.db') for p in allfiles));check('source_DB_hash_not_repo_blob',not any('DZN32_SUN_GRAPH_DOCTRINE_CORE' in p for p in allfiles))
failed=[x for x in RESULTS if x[1]=='FAIL']
for n,s,d in RESULTS: print(f'{s}\t{n}\t{d}')
print(f'SUMMARY\tPASS={len(RESULTS)-len(failed)}\tFAIL={len(failed)}');sys.exit(1 if failed else 0)
